version: "3.8"

services:
  cloudapp:
    image: farcryer2/cloudapp
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --interval 60 cloudapp